### ISSUE TITLE
Can I set any value larger than max?

### ISSUE THREAD

**Issue by FNsi** [datasone/setup_var.efi#10]
Would like to try😅

**Comment by FNsi** [comment]
I can prove it works fine.

**Comment by datasone** [comment]
I'm not quite sure what you mean by max, maybe you can write a bit more about the details?

I guess you are trying to provide larger value than the intended size, that will be limited by `VALUE_SIZE`.

**Comment by FNsi** [comment]
> I'm not quite sure what you mean by max, maybe you can write a bit more about the details?
> 
> 
> 
> I guess you are trying to provide larger value than the intended size, that will be limited by `VALUE_SIZE`.

Nah, that's the  something in the text file 


_Flags: 0x12, Size: 32, Min: 0x200, Max: 6x1000, Step: 6x0_

**Comment by FNsi** [comment]
> > > I'm not quite sure what you mean by max, maybe you can write a bit more about the details?
> 
> > > I guess you are trying to provide larger value than the intended size, that will be limited by `VALUE_SIZE`.
> 
> > 
> 
> > Nah, it's something in the text file
> 
> > 
> 
> > _Flags: 0x12, Size: 32, Min: 0x200, Max: 6x1000, Step: 6x0_
> 
> > 
> 
> > And I agree with you, the only limit is the value_size!!
> 
> 
> 
> Oh, that text describes the intended value range in the firmware setup.
> 
> 
> 
> This tool will only change corresponding value in settings storage, but how to interpret and apply the value depend on the firmware. So writing any value (within specified size) is valid for the tool, though it may be invalid for your firmware.

Yep, and I am lucky hhaa.
