### ISSUE TITLE
delete uefi wpbt

### ISSUE THREAD

**Issue by zhjygit** [datasone/setup_var.efi#18]
![09a2f52ab6d66c9c5aad27482d08468](https://github.com/datasone/setup_var.efi/assets/44870751/29a806d6-ef74-44d3-85b2-e5c31e8b5ede)
As above shown, there is a wpbt in my lenovo PC bios.
My info of dxdiag is as follows:
![image](https://github.com/datasone/setup_var.efi/assets/44870751/362f5297-7d89-4720-a664-6b1d61cbb97e)

How can i delete this wpbt module via the setup_var.efi?

**Comment by datasone** [comment]
Removing UEFI modules should be done by flashing modified BIOS ROMs.
`setup_var.efi` can only be used to modify storage in NVRAM. If some UEFI settings can be used to disable the WBPT table, it can be achiveved in 3this way. Though I don't think it's possible in current firmwares.
