### ISSUE TITLE
beware of differences between Universal-IFR-Extractor and IFRExtractor-RS

### ISSUE THREAD

**Issue by BoringBoredom** [datasone/setup_var.efi#2]
The output is significantly different in the new Rust version of the parser. E.g. [Size](https://github.com/LongSoft/IFRExtractor-RS/issues/10#issuecomment-1312919467) is missing at the moment.

**Comment by datasone** [comment]
Yes, the tool in the guide should be changed back to the original one until that issue is resolved.
Temporarily solved in d0e3176

**Comment by BoringBoredom** [comment]
https://github.com/LongSoft/IFRExtractor-RS/releases

The latest version reached feature parity. `Size` is shown in bits now (previously bytes).
