### ISSUE TITLE
Input from file doesn't work

### ISSUE THREAD

**Issue by a1rb0rn3** [datasone/setup_var.efi#24]
I try to use your tool with an input file but this doesn't seem to work.

For example, if one just follows the documentation on how to use input file the issue can be easily recreated. Modifying some variable works (for simplicity i just use the variable offset and value from your documentation in my issue here):

```
setup_var.efi CpuSetup:0x10E=0x1A > vars.txt
```

But then loading it afterwards is not working:

```
setup_var.efi < vars.txt
```

It does not print any error but just the "Usage" like when executing `setup_var.efi -h`.

For my setup i used different UEFI shells to get it to work but even using the latest UEFI shell i build with edk2-stable202408 i couldn't get it to work.

I build `setup_var.efi` using the latest state of the `master` branch.

**Comment by datasone** [comment]
Thanks for reporting this, the problem should be fixed in the [0.3.0](https://github.com/datasone/setup_var.efi/releases/tag/0.3.0) release.
