### ISSUE TITLE
With multiple varstores named "Setup", using -i to select the variable ID has no effect

### ISSUE THREAD

**Issue by terminatorul** [datasone/setup_var.efi#4]
I have Gigaybte X470 AORUS GAMING 5 WiFi F63c, which has two variables named Setup.

setup_var.efi lists both of them and asks to rerun with the variable ID for selecting one of the two variables

But when I re-run with -i option, the exact same thing happens again (option -i has no effect)

**Comment by datasone** [comment]
Can you try this version and see if it works? I think it's due to a silly bug in argument parsing...
[setup_var_issue4_1.zip](https://github.com/datasone/setup_var.efi/files/10062349/setup_var_issue4_1.zip)

**Comment by terminatorul** [comment]
Yes, it worked now and it read my byte ! I was trying to enable ReBAR option, which IFR shows is at offset 0x275 in my UEFI "Setup" variable, and setup_var.efi shows var_id 0x1 as the larger (valid) varstore.

The initial output line you included also showed the right value "var_id: Some(1)"  from my comman line.

**Comment by datasone** [comment]
Fixed in [0.1.1](https://github.com/datasone/setup_var.efi/releases/tag/v0.1.1). Thanks for the report!
