### ISSUE TITLE
[BUG] `--write_on_demand`

### ISSUE THREAD

**Issue by dreamwhite** [datasone/setup_var.efi#8]
Good evening and thank you so much for taking care of issue #7. I can confirm that the bug got solved with the newest release.
About the newest release, I noticed that there's a new argument (`--write_on_demand`) which aims to avoid useless writes on the offset unless it has a different value.

In theory this is a good practice, but in the real-life tests, it seems that this argument is simply ignored, as I read `Written offset blablabla`. Is this just a matter of a wrong print statement, or the argument isn't properly parsed?

From my very low RUST knowledge, the argument is properly parsed ([source](https://github.com/datasone/setup_var.efi/commit/07ada915496ad96f82beb88170e2b72b4cc76230#diff-23af5356f6001cd3993cd3c801fb7716ea02d1e504081b9fb569332db6107e80R156)).

**Comment by datasone** [comment]
Oh... I forgot to change the prompt text, the logic should have been working correctly in 0.2.0.
Patch for this has been added in [0.2.1](https://github.com/datasone/setup_var.efi/releases/tag/0.2.1).

**Comment by dreamwhite** [comment]
Thank you so much! I'm going to test it this afternoon and report you back, despite from the source code the prompt text is correctly displayed, just to double check it
