### ISSUE TITLE
[Feature request] Add argument to reboot 

### ISSUE THREAD

**Issue by 1alessandro1** [datasone/setup_var.efi#9]
Hello, I am very happy to know that this project exists. Amazing job.

I immediately shared it with my friend @dreamwhite and I saw he has already pinged you to fix some niche things ad discrepancies, it's so nice to see that you've quickly fixed everything he noticed that was broken/missing :)
 
By the way, we're mostly using this tool for BIOS mods (DVMT Pre Allocated / CFG Lock etc) but I have a weird laptop where the trackpad works for Linux and Windows when I set it to APIC interrupt, and this mode is unsupported for macOS; on the other hand, GPIO interrupt works for macOS but not for Windows/Linux. 

This tool comes very handy in conjuction with OpenCore Tools section, where you can send parameters when launching an option in the picker. However, after launching the tool, the user is forced to soft shutdown by pressing once the button (no force shutdown) and then boot back again with the edited BIOS option.

Would it be possible to set an argument to reboot after the change is applied to speed things up?

something like

```
setup_var.efi 0x2CA 0x01 -n Setup --reboot
```

**Comment by datasone** [comment]
Of course :)
A new argument (-r/--reboot) has been added in [0.2.2](https://github.com/datasone/setup_var.efi/releases/tag/0.2.2).
